// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMq0lv8DtYRU2OWh2yZP4WVA6FxdBZBsY',
    appId: '1:592919054069:ios:c7214bee3581b14eac27bc',
    messagingSenderId: '592919054069',
    projectId: 'excel-analysis-6052c',
    databaseURL: 'https://excel-analysis-6052c-default-rtdb.firebaseio.com',
    storageBucket: 'excel-analysis-6052c.firebasestorage.app',
    iosBundleId: 'com.eagle.excelFile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiYQ37cos3xzJ40oeCRRIIRoc_HiS9pZk',
    appId: '1:592919054069:web:fdbee1d8c56c1004ac27bc',
    messagingSenderId: '592919054069',
    projectId: 'excel-analysis-6052c',
    authDomain: 'excel-analysis-6052c.firebaseapp.com',
    databaseURL: 'https://excel-analysis-6052c-default-rtdb.firebaseio.com',
    storageBucket: 'excel-analysis-6052c.firebasestorage.app',
    measurementId: 'G-ZEHDCVJW1Q',
  );
}
